// Generated by scripts/generate-governor-delivery-manifest.mjs. Do not edit.
import generated from "./governor-host-delivery-build-manifest.generated.json" with { type: "json" };
export const GOVERNOR_DELIVERY_BUILD_MANIFEST = generated.manifest;
export const GOVERNOR_DELIVERY_BUILD_MANIFEST_DIGEST = generated.digest;
