/** Store-owner entries for the durable boundary inventory. */
import {
  governorDurableBoundary as boundary,
  type GovernorDurableBoundary,
} from "./governor-durable-boundary-contract.js";

export const GOVERNOR_DURABLE_OWNER_BOUNDARIES: readonly GovernorDurableBoundary[] = [
  boundary(
    "task-ingress-recovery",
    "src/tasks/governor/store-ingress.ts",
    "runRecoverableIngressWrite",
    "read-write",
    ["runOpenClawStateWriteTransaction", "tasks.reconcilePrimary"],
  ),
  boundary(
    "task-commit-recovery",
    "src/tasks/governor/store.ts",
    "runRecoverableTaskWrite",
    "read-write",
    ["runOpenClawStateWriteTransaction", "tasks.reconcilePrimary"],
  ),
  boundary(
    "task-startup-reconciliation",
    "src/tasks/governor/store-bootstrap.ts",
    "createGovernorStoreDependencies",
    "read-write",
    ["runOpenClawStateWriteTransaction", "tasks.reconcilePrimary"],
  ),
  boundary(
    "action-intent-owner",
    "src/tasks/governor/action-intent-store.ts",
    "GovernorActionIntentStore",
    "read-write",
    ["assertGovernorPersistedJson", "parseGovernorActionIntent", "bindGovernorActionIntent"],
  ),
  boundary(
    "action-revocation-reconcile",
    "src/tasks/governor/action-approval-reconciliation.ts",
    "reconcileRevokedGovernorActionIntent",
    "read-write",
    ["assertGovernorPersistedJson", "parseGovernorActionIntent", "bindGovernorActionIntent"],
  ),
  boundary(
    "approval-owner",
    "src/tasks/governor/approval-store.ts",
    "GovernorApprovalGrantStore",
    "read-write",
    ["assertGovernorPersistedJson", "parseGrant", "bindGrant"],
  ),
  boundary("approval-epoch-read", "src/tasks/governor/approval-store.ts", "primaryEpoch", "read", [
    "selectFrom",
    "normalizeSqliteNumber",
  ]),
  boundary(
    "checkpoint-owner",
    "src/tasks/governor/checkpoint-store.ts",
    "GovernorCheckpointStore",
    "read",
    ["parseCheckpoint", "selectFrom"],
  ),
  boundary("fanout-owner", "src/tasks/governor/fanout.ts", "GovernorFanoutStore", "read-write", [
    "assertGovernorPersistedJson",
    "parseJob",
    "bindJob",
  ]),
  boundary("fanout-job-read", "src/tasks/governor/fanout-lifecycle.ts", "loadJob", "read", [
    "parseJob",
    "selectFrom",
  ]),
  boundary(
    "fanout-physical-cancel",
    "src/tasks/governor/fanout-physical.ts",
    "applyCancellationFence",
    "write",
    ["assertGovernorPersistedJson", "requestCancellation", "replaceJob"],
  ),
  boundary(
    "fanout-physical-release",
    "src/tasks/governor/fanout-physical.ts",
    "reconcileReleasedJob",
    "write",
    ["assertGovernorPersistedJson", "coordinator.state", "replaceJob"],
  ),
  boundary(
    "fanout-physical-reconcile",
    "src/tasks/governor/fanout-physical.ts",
    "reconcileFanoutPhysicalState",
    "read-write",
    ["assertGovernorPersistedJson", "parseJob", "coordinator.state"],
  ),
  boundary(
    "fanout-physical-request",
    "src/tasks/governor/fanout-physical.ts",
    "requestFanoutCancellation",
    "write",
    ["assertGovernorPersistedJson", "applyCancellationFence", "replaceJob"],
  ),
  boundary(
    "memory-authority-owner",
    "src/tasks/governor/memory-authority.ts",
    "GovernorMemoryAuthorityStore",
    "read-write",
    ["assertGovernorPersistedJson", "parseGovernorMemory", "bindGovernorMemory"],
  ),
  boundary(
    "memory-contradiction-owner",
    "src/tasks/governor/memory-contradiction-store.ts",
    "GovernorMemoryContradictionStore",
    "read-write",
    ["assertGovernorPersistedJson", "parseGovernorMemory", "bindGovernorMemory"],
  ),
  boundary(
    "memory-replacement-current-read",
    "src/tasks/governor/memory-replacement-validator.ts",
    "loadCurrentGovernorMemoryReplacement",
    "read",
    ["loadCurrentGovernorEvidenceInTransaction", "authority.state", "parseGovernorMemory"],
  ),
  boundary(
    "memory-store-owner",
    "src/tasks/governor/memory-integrity.ts",
    "GovernorMemoryStore",
    "read-write",
    ["assertGovernorPersistedJson", "parseGovernorMemory", "bindGovernorMemory"],
  ),
  boundary(
    "memory-repair-state-update",
    "src/tasks/governor/memory-repair-state-store.ts",
    "updateGovernorMemoryRepairState",
    "read-write",
    ["assertGovernorPersistedJson", "assertGovernorMemoryRepairMutationCurrent", "updated_at"],
  ),
  boundary(
    "memory-repair-state-read",
    "src/tasks/governor/memory-repair-state-store.ts",
    "loadRepair",
    "read",
    ["parseGovernorMemoryRemediation", "selectFrom"],
  ),
  boundary(
    "memory-repair-state-requeue",
    "src/tasks/governor/memory-repair-state-store.ts",
    "requeueGovernorMemoryRepair",
    "read-write",
    ["assertGovernorPersistedJson", "assertGovernorMemoryRepairMutationCurrent", "updated_at"],
  ),
  boundary(
    "outbox-owner",
    "src/tasks/governor/outbox-store.ts",
    "GovernorOutboxStore",
    "read-write",
    ["assertGovernorPersistedJson", "parseOutbox", "bindGovernorOutbox"],
  ),
  boundary(
    "store-query-owner",
    "src/tasks/governor/store-queries.ts",
    "GovernorStoreQueries",
    "read",
    ["loadGovernorTask", "parseEventRow", "parseEffectRow"],
  ),
  boundary(
    "store-evidence-read",
    "src/tasks/governor/store-queries.ts",
    "loadGovernorEvidence",
    "read",
    ["parseEvidenceRow", "selectFrom"],
  ),
  boundary(
    "task-authority-owner",
    "src/tasks/governor/task-authority.ts",
    "GovernorTaskAuthorityStore",
    "read-write",
    ["parseTaskRow", "authority.reconcile", "authority.matches"],
  ),
  boundary(
    "host-delivery-primary-read",
    "src/security/governor-host-delivery-persistence.ts",
    "primaryBindingMatches",
    "read",
    ["selectFrom", "normalizeSqliteNumber"],
  ),
  boundary(
    "host-delivery-primary-write",
    "src/security/governor-host-delivery-persistence.ts",
    "writePrimaryCertification",
    "write",
    ["insertInto", "certification_signature"],
  ),
  boundary(
    "host-delivery-started-read",
    "src/security/governor-host-delivery-persistence.ts",
    "hasStartedEffect",
    "read",
    ["selectFrom", "effect_started"],
  ),
  boundary(
    "host-approval-epoch-read",
    "src/security/governor-host-persistence.ts",
    "primaryApprovalEpoch",
    "read",
    ["selectFrom", "normalizeSqliteNumber"],
  ),
  boundary(
    "host-approval-epoch-write",
    "src/security/governor-host-persistence.ts",
    "writeApprovalEpoch",
    "write",
    ["insertInto", "onConflict"],
  ),
  boundary(
    "host-approval-running-read",
    "src/security/governor-host-persistence.ts",
    "requestStartedApprovalCancellation",
    "read-write",
    ["selectFrom", "updateTable", "effect_started_at"],
  ),
  boundary(
    "host-approval-unstarted-cancel",
    "src/security/governor-host-persistence.ts",
    "cancelUnstartedApprovalExecutions",
    "read-write",
    ["selectFrom", "updateTable", "effect_started_at"],
  ),
] as const;
