/** Security-owned CI inventory of governor durable readers and writers. */
import type { GovernorDurableBoundary } from "./governor-durable-boundary-contract.js";
import { GOVERNOR_DURABLE_OWNER_BOUNDARIES } from "./governor-durable-boundary-owners.js";
import { GOVERNOR_RAW_DURABLE_BOUNDARIES } from "./governor-durable-boundary-schema.js";

export type { GovernorDurableBoundary } from "./governor-durable-boundary-contract.js";

export const GOVERNOR_DURABLE_BOUNDARIES: readonly GovernorDurableBoundary[] = [
  ...GOVERNOR_RAW_DURABLE_BOUNDARIES,
  {
    id: "task-ingress",
    file: "src/tasks/governor/store-ingress.ts",
    symbol: "ingestGovernorTask",
    direction: "read-write",
    enforcementAnchors: [
      "assertGovernorPersistedJson",
      "parseTaskRow",
      "bindTask",
      "tasks.prepare",
    ],
  },
  {
    id: "task-commit",
    file: "src/tasks/governor/store.ts",
    symbol: "commit",
    direction: "read-write",
    enforcementAnchors: ["validateGovernorCommitPayload", "parseTaskRow", "tasks.prepare"],
  },
  {
    id: "task-commit-validation",
    file: "src/tasks/governor/store-commit-validation.ts",
    symbol: "validateGovernorCommitPayload",
    direction: "write",
    enforcementAnchors: [
      "assertGovernorPersistedJson",
      "bindTask",
      "bindEvent",
      "bindEffect",
      "bindGovernorOutbox",
    ],
  },
  {
    id: "task-audit-event",
    file: "src/tasks/governor/store-audit.ts",
    symbol: "appendGovernorAuditEvent",
    direction: "write",
    enforcementAnchors: ["assertGovernorPersistedJson", "parseTaskRow", "bindEvent"],
  },
  {
    id: "action-pending-reconcile",
    file: "src/tasks/governor/action-intent-store.ts",
    symbol: "listPendingIds",
    direction: "read-write",
    enforcementAnchors: [
      "loadGovernorTask",
      "parseGovernorActionIntent",
      "statusWithinTransaction",
    ],
  },
  {
    id: "action-outcome-fence",
    file: "src/tasks/governor/action-intent-store.ts",
    symbol: "validateOutcome",
    direction: "read-write",
    enforcementAnchors: [
      "assertGovernorPersistedJson",
      "loadGovernorTask",
      "parseGovernorActionIntent",
    ],
  },
  {
    id: "action-claim",
    file: "src/tasks/governor/action-intent-store.ts",
    symbol: "claim",
    direction: "read-write",
    enforcementAnchors: [
      "assertGovernorPersistedJson",
      "loadGovernorTask",
      "bindGovernorActionIntent",
    ],
  },
  {
    id: "action-effect-start",
    file: "src/tasks/governor/action-execution-lifecycle.ts",
    symbol: "beginGovernorActionEffect",
    direction: "read-write",
    enforcementAnchors: [
      "assertGovernorPersistedJson",
      "loadGovernorTask",
      "parseGovernorActionIntent",
    ],
  },
  {
    id: "action-termination",
    file: "src/tasks/governor/action-execution-lifecycle.ts",
    symbol: "acknowledgeGovernorActionTermination",
    direction: "read-write",
    enforcementAnchors: [
      "assertGovernorPersistedJson",
      "loadGovernorTask",
      "bindGovernorActionIntent",
    ],
  },
  {
    id: "approval-admission",
    file: "src/tasks/governor/approval-store.ts",
    symbol: "admitAuthenticatedApproval",
    direction: "write",
    enforcementAnchors: [
      "assertGovernorPersistedJson",
      "verifyApprovalReceiptCurrent",
      "bindGrant",
    ],
  },
  {
    id: "delivery-certification",
    file: "src/tasks/governor/delivery-certification-store.ts",
    symbol: "resolveCertified",
    direction: "read-write",
    enforcementAnchors: [
      "assertGovernorPersistedJson",
      "resolver.resolve",
      "certification_signature",
    ],
  },
  {
    id: "fanout-enqueue",
    file: "src/tasks/governor/fanout.ts",
    symbol: "enqueue",
    direction: "read-write",
    enforcementAnchors: ["assertGovernorPersistedJson", "this.#task", "bindJob"],
  },
  {
    id: "fanout-claim",
    file: "src/tasks/governor/fanout.ts",
    symbol: "claimNext",
    direction: "read-write",
    enforcementAnchors: ["assertGovernorPersistedJson", "this.#task", "parseJob"],
  },
  {
    id: "fanout-cancel",
    file: "src/tasks/governor/fanout-lifecycle.ts",
    symbol: "cancelFanoutJob",
    direction: "read-write",
    enforcementAnchors: ["assertGovernorPersistedJson", "tasks.loadCurrent", "loadJob"],
  },
  {
    id: "fanout-heartbeat",
    file: "src/tasks/governor/fanout-lifecycle.ts",
    symbol: "heartbeatFanoutJob",
    direction: "read-write",
    enforcementAnchors: ["assertGovernorPersistedJson", "tasks.loadCurrent", "loadJob"],
  },
  {
    id: "fanout-termination",
    file: "src/tasks/governor/fanout-lifecycle.ts",
    symbol: "acknowledgeFanoutTermination",
    direction: "read-write",
    enforcementAnchors: ["assertGovernorPersistedJson", "tasks.loadCurrent", "loadJob"],
  },
  {
    id: "fanout-orphan-termination",
    file: "src/tasks/governor/fanout-lifecycle.ts",
    symbol: "acknowledgeOrphanedFanoutTermination",
    direction: "read-write",
    enforcementAnchors: ["assertGovernorPersistedJson", "tasks.loadCurrent", "receipt"],
  },
  {
    id: "fanout-completion",
    file: "src/tasks/governor/fanout-completion.ts",
    symbol: "completeFanoutJob",
    direction: "read-write",
    enforcementAnchors: ["assertGovernorPersistedJson", "tasks.loadCurrent", "bindEnvelope"],
  },
  {
    id: "fanin-claim",
    file: "src/tasks/governor/fanin-reducer-store.ts",
    symbol: "claim",
    direction: "read-write",
    enforcementAnchors: ["assertGovernorPersistedJson", "parseEnvelope", "parseReducerResult"],
  },
  {
    id: "fanin-complete",
    file: "src/tasks/governor/fanin-reducer-store.ts",
    symbol: "complete",
    direction: "read-write",
    enforcementAnchors: ["assertGovernorPersistedJson", "this.#task", "result_digest"],
  },
  {
    id: "memory-candidate",
    file: "src/tasks/governor/memory-integrity.ts",
    symbol: "storeCandidate",
    direction: "write",
    enforcementAnchors: [
      "assertGovernorPersistedJson",
      "assertGovernorBoundarySafe",
      "bindGovernorMemory",
    ],
  },
  {
    id: "memory-promotion",
    file: "src/tasks/governor/memory-integrity.ts",
    symbol: "promoteVerified",
    direction: "read-write",
    enforcementAnchors: [
      "assertGovernorPersistedJson",
      "loadCurrentGovernorEvidenceInTransaction",
      "authority.protect",
    ],
  },
  {
    id: "memory-recall",
    file: "src/tasks/governor/memory-integrity.ts",
    symbol: "retrieve",
    direction: "read-write",
    enforcementAnchors: [
      "assertGovernorPersistedJson",
      "authority.reconcile",
      "parseGovernorMemory",
    ],
  },
  {
    id: "memory-quarantine",
    file: "src/tasks/governor/memory-integrity.ts",
    symbol: "quarantine",
    direction: "read-write",
    enforcementAnchors: [
      "assertGovernorPersistedJson",
      "parseGovernorMemory",
      "bindGovernorMemory",
    ],
  },
  {
    id: "memory-forget",
    file: "src/tasks/governor/memory-integrity.ts",
    symbol: "forget",
    direction: "read-write",
    enforcementAnchors: ["assertGovernorPersistedJson", "authority.retire", "bindGovernorMemory"],
  },
  {
    id: "memory-contradiction",
    file: "src/tasks/governor/memory-contradiction-store.ts",
    symbol: "resolve",
    direction: "read-write",
    enforcementAnchors: [
      "assertGovernorPersistedJson",
      "assertCurrentExecution",
      "this.#evidence",
      "bindGovernorMemory",
    ],
  },
  {
    id: "memory-repair-update",
    file: "src/tasks/governor/memory-contradiction-store.ts",
    symbol: "updateRepairState",
    direction: "read-write",
    enforcementAnchors: ["updateGovernorMemoryRepairState", "tasks: this.#tasks", "guard"],
  },
  {
    id: "memory-repair-requeue",
    file: "src/tasks/governor/memory-contradiction-store.ts",
    symbol: "requeueRepair",
    direction: "read-write",
    enforcementAnchors: ["requeueGovernorMemoryRepair", "tasks: this.#tasks", "guard"],
  },
  {
    id: "memory-repair-verify",
    file: "src/tasks/governor/memory-contradiction-store.ts",
    symbol: "verifyRepair",
    direction: "read-write",
    enforcementAnchors: [
      "assertGovernorPersistedJson",
      "this.#evidence",
      "bindGovernorMemoryRemediation",
    ],
  },
  {
    id: "outbox-claim",
    file: "src/tasks/governor/outbox-store.ts",
    symbol: "claim",
    direction: "read-write",
    enforcementAnchors: ["assertGovernorPersistedJson", "tasks.loadCurrent", "parseOutbox"],
  },
  {
    id: "outbox-sent",
    file: "src/tasks/governor/outbox-store.ts",
    symbol: "markSent",
    direction: "read-write",
    enforcementAnchors: [
      "assertGovernorPersistedJson",
      "isGovernorVerifiedDeliveryReceipt",
      "bindGovernorOutbox",
    ],
  },
  {
    id: "outbox-shadow",
    file: "src/tasks/governor/outbox-store.ts",
    symbol: "markWouldSend",
    direction: "read-write",
    enforcementAnchors: ["assertGovernorPersistedJson", "markSent"],
  },
  {
    id: "outbox-manual-review",
    file: "src/tasks/governor/outbox-store.ts",
    symbol: "markManualReview",
    direction: "read-write",
    enforcementAnchors: ["assertGovernorPersistedJson", "parseOutbox", "bindGovernorOutbox"],
  },
  {
    id: "host-approval-persistence",
    file: "src/security/governor-host-persistence.ts",
    symbol: "createGovernorHostPersistence",
    direction: "read-write",
    enforcementAnchors: [
      "governorPrimaryHasDurableState",
      "createGovernorHostAntiRollbackLedger",
      "runOpenClawStateWriteTransaction",
    ],
  },
  {
    id: "host-delivery-persistence",
    file: "src/security/governor-host-delivery-persistence.ts",
    symbol: "createGovernorHostDeliveryPersistence",
    direction: "read-write",
    enforcementAnchors: [
      "assertGovernorPersistedJson",
      "ledger.state",
      "runOpenClawStateWriteTransaction",
    ],
  },
  {
    id: "host-owner-ingress-persistence",
    file: "src/security/governor-host-owner-ingress-persistence.ts",
    symbol: "createGovernorOwnerIngressPersistence",
    direction: "read-write",
    enforcementAnchors: [
      "assertGovernorPersistedJson",
      "parseReceipt",
      "runOpenClawStateWriteTransaction",
    ],
  },
  {
    id: "host-ledger-storage",
    file: "src/security/governor-host-ledger-storage.ts",
    symbol: "createGovernorLedgerStorage",
    direction: "read-write",
    enforcementAnchors: ["loadAndRepair", "createGovernorLedgerEntry", "replaceHead"],
  },
  {
    id: "host-canary-receipt",
    file: "src/security/governor-host-canary-sink.ts",
    symbol: "createCanaryHostSender",
    direction: "read-write",
    enforcementAnchors: ["assertGovernorPersistedJson", "payloadDigest", "delivery_key"],
  },
  ...GOVERNOR_DURABLE_OWNER_BOUNDARIES,
  {
    id: "codec-task-event-effect-evidence",
    file: "src/tasks/governor/store-codec.ts",
    symbol: "parseTaskRow",
    direction: "read",
    enforcementAnchors: [
      "parseGovernorStoredJson",
      "projection_digest",
      "assertOpaqueGovernorScope",
    ],
  },
  {
    id: "codec-fanout-job",
    file: "src/tasks/governor/fanout-codec.ts",
    symbol: "parseJob",
    direction: "read",
    enforcementAnchors: [
      "parseGovernorStoredJson",
      "assertGovernorPersistedJson",
      "governorFanoutJobDigest",
    ],
  },
  {
    id: "codec-fanout-job-write",
    file: "src/tasks/governor/fanout-codec.ts",
    symbol: "replaceJob",
    direction: "write",
    enforcementAnchors: ["bindJob", "governorFanoutJobDigest", "job_digest"],
  },
  {
    id: "codec-fanin-envelope",
    file: "src/tasks/governor/fanout-codec.ts",
    symbol: "parseEnvelope",
    direction: "read",
    enforcementAnchors: ["parseGovernorStoredJson", "governorFaninEnvelopeDigest"],
  },
  {
    id: "codec-outbox",
    file: "src/tasks/governor/outbox-codec.ts",
    symbol: "parseGovernorOutbox",
    direction: "read",
    enforcementAnchors: [
      "parseGovernorStoredJson",
      "governorOutboxDeliveryKey",
      "governorOutboxRecordDigest",
    ],
  },
] as const;
